### ISSUE TITLE
Feature Request: Enable use of "slug" for device roles instead of full role name

### ISSUE THREAD

**Issue by bdlamprecht** [AAbouZaid/netbox-as-ansible-inventory#4]
I appreciate the effort you've put into this code.
It has the potential to work great for what I've got in mind for a proof-of-concept project I'm working on.

Currently, only the actual "device_role" can be used within Ansible to group hosts (I believe).
Would it be possible to have the option (perhaps within the 'netbox.yml' file) to use the "slug" of the role instead of the full role name?

**Comment by AAbouZaid** [comment]
It's an interesting idea ... actually `name` is used.
I will check it asap.

**Comment by rthomson** [comment]
I'm also interested in being able to use `slug` instead of `name`, but not just as an either/or but in combinations of the two, depending on the netbox fields.

I have a working implementation that adds `names` and `slugs` as valid sections to `group_by` and `host_vars` (essentially replacing `general` but leaving it also in place for backwards compat) so that someome can choose which netbox fields they want in ansible from either `name` or `slug` on a per-field basis.

Example `netbox.yml` that I'm working with (for "virtual machine" records in modern netbox):

```
netbox:
    main:
        api_url: 'https://localhost/api/virtualization/virtual-machines/'

    group_by:
        names:
            - cluster
        slugs:
            - platform
        custom:
            - ansible_groups

    hosts_vars:
        ip:
            netbox_primary_ip: primary_ip
            ansible_host: primary_ip
        names:
            netbox_cluster: cluster
            netbox_vcpus: vcpus
            netbox_memory: memory
            netbox_disk: disk
            netbox_tenant: tenant
        slugs:
            netbox_role: role
            netbox_platform: platform
        labels:
            netbox_status: status
        custom:
            ansible_user: ansible_user
            ansible_port: ansible_port
```

I'm happy to fire off a pull request if this looks interesting.
