### ISSUE TITLE
AttributeError: module 'ansible.plugins.inventory.netbox' has no attribute 'InventoryModule'

### ISSUE THREAD

**Issue by cventastic** [AAbouZaid/netbox-as-ansible-inventory#41]
Hello, 

I have the following problem. When I try:
`ansible-inventory -i inventory/netbox.py --list -vvv` or 
`ansible -i inventory/netbox.py netbox.yml -m ping -vvv`
I get:
`AttributeError: module 'ansible.plugins.inventory.netbox' has no attribute 'InventoryModule'`

I have tried with ansible 2.7.1 and ansible 2.9.0. With python2.7 and python3.5.

I put netbox.py into /home/inventory and configured ansible.cfg like this:
`inventory_plugins = /home/inventory`

My YAML File looks like this:

```
plugin: netbox
api_endpoint: https://my.netbox.com
token: *****
validate_certs: True
config_context: False
group_by:
    default:
        - sites
```

What am I doing wrong?

At least I am not alone, see [Stackoverflow](https://stackoverflow.com/questions/53955400/ansible-inventory-plugin-netbox)

**Comment by cventastic** [comment]
I fixed this issue by correcting my yml file:
```
netbox:
    main:
        api_url: 'https://my.netbox.com/api/dcim/devices/'
        api_token: '*****'

    group_by:
        default:
        - id

    hosts_vars:
        ip:
            ansible_ssh_host: primary_ip
```
